### ISSUE TITLE
Please update the README to include Project Team Accomplishments for Philly

### ISSUE THREAD

**Issue by jacebryan** [SFDO-Community-Sprints/transfer-equivalency#32]
Hello transfer-equivalency team!

Please ask your Scribe to update the Project Team Accomplishments for Philly.

Thank you! :)

**Comment by robertbwatson** [comment]
@MatthewBlanski You helped on something at the Philadelphia sprint related to this project, didn't you? If so, can you update the readme section to call out any additional work that was done?
